### ISSUE TITLE
can l modify ripple color effect

### ISSUE THREAD

**Issue by yuaneko95** [skydoves/PowerMenu#102]

**Comment by sebastienrouif** [comment]
How are you building your menu?
I you are using Material, the ripple should come from `colorControlHighlight` theme attribute which you could add here 
https://github.com/skydoves/PowerMenu/blob/main/app/src/main/res/values/styles.xml#L36 in `PopupCardThemeOverlay`

**Comment by yuaneko95** [comment]
here is my code

![image](https://user-images.githubusercontent.com/98723152/221492899-ead0e183-32de-4d46-9cd0-eae99b3ee002.png)

I'm still confused about how to change the ripple color

**Comment by sebastienrouif** [comment]
Check how the theme overlay is applied in https://github.com/skydoves/PowerMenu/blob/main/app/src/main/java/com/skydoves/powermenudemo/PowerMenuUtils.java#L143 
inseatd of calling `requireActivity()` use a styled context and add your ripple colour to `PopupCardThemeOverlay` in https://github.com/skydoves/PowerMenu/blob/main/app/src/main/res/values/styles.xml#L36
```
  <style name="PopupCardThemeOverlay">
    <item name="materialCardViewStyle">@style/PopupCardStyle</item>
    <item name="colorControlHighlight">#0ff</item>
  </style>
  ```

**Comment by sebastienrouif** [comment]
Did it solve your problem?

**Comment by yuaneko95** [comment]
yes it's solve my problem. thanks
