### ISSUE TITLE
Lifecycle dependencies need to be updated to 2.6.0 they have conflicts with 2.5.1

### ISSUE THREAD

**Issue by vullnetlimani** [skydoves/PowerMenu#103]
- Library Version 2.2.2
- Affected Device(s) All Devices
 
It's not a big issue the project can build and compile, but I have annoying warnings Android Studio is crying because of that, and when I exclude the lifecycle from the library it continues to cry, so whenever you have time please have a look into it.

**Comment by RobbWatershed** [comment]
+1

**Comment by skydoves** [comment]
A new version 2.2.3 was released.

**Comment by RobbWatershed** [comment]
Awesome. Thank you~
