### ISSUE TITLE
click for menu item is not happening on Custom Power Menu 

### ISSUE THREAD

**Issue by dileepkantapop** [skydoves/PowerMenu#2]
I tried integrating Power menu in my project but the click is not happening. I tried keeping an log also but its not going inside loop.
  customPowerMenu = new CustomPowerMenu.Builder<>(MapsActivityNew.this, new IconMenuAdapter())
                 .setWith(550)
                 .setHeight(780)
                .addItem(new MapMenuFilter(false, "XXXX"))
                .addItem(new MapMenuFilter(false, "XXXX"))
                .setAnimation(MenuAnimation.SHOWUP_BOTTOM_RIGHT)
                .setMenuRadius(10f)
                .setMenuShadow(10f)
                .build();

 private OnMenuItemClickListener<MapMenuFilter> onIconMenuItemClickListener = new OnMenuItemClickListener<MapMenuFilter>() {
        @Override
        public void onItemClick(int position, MapMenuFilter item) {
            Log.e("Selected",item.getFilterName()+" << >> "+position);
        }
    };

**Comment by skydoves** [comment]
Hi!
You didn't use .setOnMenuItemClickListener(onMenuItemClickListener) method.
Try after add a setOnMenuItemClickListener(onIconMenuItemClickListener) on CustomPowerMenu.Builder

**Comment by dileepkantapop** [comment]
Hi,

i was using it.
Sorry, by mistakenly that code got deleted on previous comment. 

 customPowerMenu = new CustomPowerMenu.Builder<>(MapsActivityNew.this, new IconMenuAdapter())
                 .setWith(550)
                 .setHeight(780)
                .addItem(new MapMenuFilter(false, "XXXX"))
          
                .setOnMenuItemClickListener(new OnMenuItemClickListener<MapMenuFilter>() {
                    @Override
                    public void onItemClick(int position, MapMenuFilter item) {
                        Log.e("Selected",item.getFilterName()+" << >> "+position);
                    }
                })
                .setAnimation(MenuAnimation.SHOWUP_BOTTOM_RIGHT)
                .setMenuRadius(10f)
                .setMenuShadow(10f)
                .build();

**Comment by skydoves** [comment]
I think your custom items are focusable.
then descent your item layout's focusability like below.

<LinearLayout xmlns:android=”http://schemas.android.com/apk/res/android”
android:layout_width=”match_parent”
android:layout_height=”match_parent”
android:descendantFocusability=”blocksDescendants”>

**Comment by dileepkantapop** [comment]
Hi,

That too is not working,

i have a Map and with a button click i am assigning the custompowermenu with the adapter with model class.
i have a checkbox in adapter its getting click too but the menu item is not getting click.

When i am debugging it its saying me Custom power menu null

**Comment by skydoves** [comment]
Oh, can you push your example project on your repository?

**Comment by skydoves** [comment]
Then add attributes on your checkbox like below.
```xml
<CheckBox
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:focusable="false"
        android:focusableInTouchMode="false"/>
```

**Comment by dileepkantapop** [comment]
Hi,
Thanks for the quick response.
i really appreciate your time and support.
Its working fine

**Comment by skydoves** [comment]
You're welcome 👍 ^^
