### ISSUE TITLE
Add "tag" to PowerMenuItem

### ISSUE THREAD

**Issue by mlipmanx** [skydoves/PowerMenu#22]
This is an enhancement:

Add a "tag" member to PowerMenuItem to pass related information. Ideally, there should be an additional constructor and an inherited type-safe version (eg PowerMenuItem&lt;TagType&gt;

Issue is that currently you pretty much have to do a text match on the title to find which item was clicked.

**Comment by skydoves** [comment]
@mlipmanx 
Actually PowerMenuItem is one of the example of generics item.
You can customizing by using CustomPowerMenu with String, Integer, customized class like
PowerMenuItem or whatever.
But version 2.0.5, below methods are added in PowerMenuItem class.

```java
void setTag(Object tag);
Object getTag();
```

Thanks!
