### ISSUE TITLE
error run app in emulator

### ISSUE THREAD

**Issue by dante7191** [skydoves/PowerMenu#25]
Hi.
When I add 'implementation "com.github.skydoves:powermenu:2.0.5"' build or running app become failed with this error :  "Compilation failed; see the compiler error output for details."
what should I do??
I use android studio 3.1.3 / min_sdk = 18/target_sdk=27 / buildToolsVersion= '27.0.3'
Thank you.

**Comment by skydoves** [comment]
@dante7191 
Hello :)
try '27.1.1' support library version & buildToolsVersion.
Thank you.

**Comment by dante7191** [comment]
Thank you for your reply :)
There is no buildToolsVersion 27.1.1, and 27.0.3 is last release in google android developer site!!
By the way I change both support library version & buildToolsVersion but I recieve this error: 
All packages are not available for download!  
The following packages are not available:
- Package id build-tools;27.1.1

**Comment by skydoves** [comment]
please check out below developer site!
https://developer.android.com/topic/libraries/support-library/packages
or
https://developer.android.com/topic/libraries/support-library/revisions#27-1-1

If you can not resolve support library version 27.1.1, then you can use 
implementation "com.github.skydoves:powermenu:2.0.4" than 2.0.5.
Thank you!

**Comment by dante7191** [comment]
@skydoves 
Not worked :(
Same error again (Compilation failed) with 2.0.4!!!!!

**Comment by dante7191** [comment]
actually I developed custom keyboard and I want to create popup menu on one of keyboard key.
Keyboard keys haven't view and I can't work with anchor view, I think PowerMenu can solve my issue.
So I did some work for this PowerMenu but still problem exist!!
what should I do?
