### ISSUE TITLE
setSelectedMenuColor() not available for CustomPowermenu ?

### ISSUE THREAD

**Issue by khalid-mahmood** [skydoves/PowerMenu#29]
How i can do this in CustomPowerMenu?
means change color of selected item in CustomPowerMenu!!

**Comment by skydoves** [comment]
@khalid-mahmood 
Hello,
You should write it what you want Customized MenuAdapter.
If you extends MenuBaseAdapter, you can override __setSelectedPosition__ method and do like [here].(https://github.com/skydoves/PowerMenu/blob/master/powermenu/src/main/java/com/skydoves/powermenu/MenuListAdapter.java)
