### ISSUE TITLE
menu can not click

### ISSUE THREAD

**Issue by hantu123** [skydoves/PowerMenu#3]
i down load the demo

but can not click the menu ,is there some thing wrong?

**Comment by skydoves** [comment]
would you let me know developing environment?

**Comment by hantu123** [comment]
i use android Studio 

i have nothing change your demo, just download and run it.

And

I made it according to your instructions , but there was the same problem. The menu popped out, but the click was invalid. It didn't work

**Comment by hantu123** [comment]
![qq20171119-185625](https://user-images.githubusercontent.com/5743163/32989971-6c20552a-cd5b-11e7-833b-18ff532faf29.gif)

**Comment by skydoves** [comment]
I think the last released version has problem in 8.0 Oreo.
I will found it and fix soon.

**Comment by skydoves** [comment]
@hantu123 sorry for late reply.
I faced the same problem on some devices under 4.4.2.
It was some devices are not auto-focused on listView in PopupWindow.
And it was fixed maven v1.1.0!
