### ISSUE TITLE
Release File

### ISSUE THREAD

**Issue by rkarimi88** [skydoves/PowerMenu#30]
Hi.
I can't sync gradle by adding `implementation "com.github.skydoves:powermenu:2.0.5"`.
I searched a lot, but i wasn't successful.

Would you please place ZIP or AAR file of your library in releases?
Thanks in advance.

**Comment by rkarimi88** [comment]
Wow... I don't know how to thank you... how fast...

Thanks a million! :)

**Comment by rkarimi88** [comment]
I just faced a problem....when i use it in my project, i get this error:
```
Error:(68, 26) error: cannot access LifecycleObserver
class file for android.arch.lifecycle.LifecycleObserver not found
```

is there any other lib i should add for this?

**Comment by rkarimi88** [comment]
sorry i just read [here ](https://github.com/skydoves/PowerMenu/issues/10)you've answered before.
thanks.

**Comment by rkarimi88** [comment]
I still have that Error (two posts above).
I even added runtime and viewmodel too, but it still exists....

Do you know how can i fix this problem? I'm so eager to see your menu on my project.....

**Comment by skydoves** [comment]
@rkarimi88 
well.. what is your develop environment? like target sdk version and support library version.

**Comment by rkarimi88** [comment]
Here it is:
`android {
    compileSdkVersion 25
    defaultConfig {
        applicationId "app.hrkarimi.promanagement"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}`

**Comment by rkarimi88** [comment]
Here it is:
```
android {
    compileSdkVersion 25
    defaultConfig {
        applicationId "somename"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

**Comment by skydoves** [comment]
@rkarimi88 
you should use targetSdkVersion more than 27, also support library version.

**Comment by rkarimi88** [comment]
OK, I will update and test again... I didn't know it. Thanks for your time.
