### ISSUE TITLE
Issue with setFocusable(true)

### ISSUE THREAD

**Issue by Devspm** [skydoves/PowerMenu#34]
Hi, Thanks for the library.
The problem is that the setFocusable(true) method only works when setShowBackground is set to true.
if it is set to false , the other views responds to clicks. I just want to remove the background shadow and popUp to get clicked when it is shown and not other views.

Here is my code:

powerMenu = new PowerMenu.Builder(context)
                .addItemList(powerMenuItems)
                .setShowBackground(false)
                .setLifecycleOwner(((MainActivity)context))
                .setTextColor(Color.WHITE)
                .setMenuColor(context.getResources().getColor(R.color.main_color))
                .setSelectedTextColor(Color.WHITE)
                .setSelectedMenuColor(context.getResources().getColor(R.color.colorPrimary))
                .setOnMenuItemClickListener(menuItemClickListener)
                .setFocusable(true)
                .build();

**Comment by skydoves** [comment]
@Devspm 
Hello! Sorry for late reply. Try below codes :)

```java
.setFocusable(true)
.setBackgroundAlpha(0.0f)
 .setOnBackgroundClickListener(new View.OnClickListener() {
         @Override
          public void onClick(View view) {
                   // do nothing
          }
     })
```
