### ISSUE TITLE
This library is great but WHY did you use a listview instead of recyclerview ?

### ISSUE THREAD

**Issue by pikaboo** [skydoves/PowerMenu#35]

**Comment by skydoves** [comment]
@pikaboo 
Hello!
Of course, RecyclerView has more advantages than ListView.
- ViewHolder Pattern
- LayoutManager
- Item Decorations, Animations
- OnItem TouchListener
- etc..

But this library is focused on the popup for the small list.
Not for the too big size item list.
Thank you for your issue and interests!
