### ISSUE TITLE
Error using classpath 3.2.0

### ISSUE THREAD

**Issue by 9717062617** [skydoves/PowerMenu#36]
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

**Comment by skydoves** [comment]
It seems bintray error. I'm finding the solution.
https://github.com/novoda/bintray-release/issues/213

Thank you!

**Comment by skydoves** [comment]
@9717062617 
It's fixed now!
Thank you for your issue.
