### ISSUE TITLE
Cannot customize font style

### ISSUE THREAD

**Issue by m-principe** [skydoves/PowerMenu#41]
Hello developer, can you give a guide on how to customize the font style? My app requires the default Android Roboto fonts. Thank you.

**Comment by skydoves** [comment]
@m-principe 
Hello!
Here is the example of the customizing your font using `CustomPowerMenu`.

[adapter](https://github.com/skydoves/PowerMenu/blob/master/app/src/main/java/com/skydoves/powermenudemo/customs/adapters/CenterMenuAdapter.java)
[layout](https://github.com/skydoves/PowerMenu/blob/master/app/src/main/res/layout/item_title_menu.xml)
