### ISSUE TITLE
font family

### ISSUE THREAD

**Issue by Zia-Sheikh** [skydoves/PowerMenu#50]
how to set specific font for the menu items, i mean is there any function like, powermenu.setTypeFace() ? please guide, thanks

**Comment by skydoves** [comment]
@Zia-Sheikh 
It is added on version `2.1.0`.
You can set it using the following method.
```java
.setTextTypeface(Typeface.create("sans-serif-medium", Typeface.BOLD))
```
Thank you for your issue!

**Comment by Zia-Sheikh** [comment]
> @Zia-Sheikh
> It is added on version `2.1.0`.
> You can set it using the following method.
> 
> ```java
> .setTextTypeface(Typeface.create("sans-serif-medium", Typeface.BOLD))
> ```
> 
> Thank you for your issue!

thanks @skydoves for your support
