### ISSUE TITLE
show tooltip above menu

### ISSUE THREAD

**Issue by everton15m** [skydoves/PowerMenu#51]
Hello, do you know if there is an easy way to show a tooltip arrow below the anchor and above the power menu?

**Comment by skydoves** [comment]
@everton15m 
Can you show me some examples of your thinking?

**Comment by everton15m** [comment]
https://pasteboard.co/IcSfT2U.png
Can you see the arrow indicator below the anchor ?

**Comment by everton15m** [comment]
Does anyone have any suggestions?

**Comment by everton15m** [comment]
Any updates @skydoves  ?

**Comment by skydoves** [comment]
@everton15m 
Sorry for the late reply..
I don't have any plans for implementing menu arrow now.
Maybe a few months later, If I would implement arrow feature I will let you know about the new version.
Thank you for your issue! 👍

**Comment by skydoves** [comment]
@everton15m 
Hi, I published a new library [Balloon](https://github.com/skydoves/Balloon).
A lightweight popup like tooltips, fully customizable with arrow and animations.
You can implement it using this library. :)
