### ISSUE TITLE
WRAP_CONTENT support?

### ISSUE THREAD

**Issue by airtel121** [skydoves/PowerMenu#52]
CustomPowerMenu.Builder<>(context, new CustomDialogMenuAdapter())
        .setHeaderView(R.layout.layout_custom_dialog_header)
        .setFooterView(R.layout.layout_custom_dialog_footer)
        .addItem(
            new NameCardMenuItem(
                context.getResources().getDrawable(R.drawable.face3),
                "Sophie",
                context.getString(R.string.board3)))
        .setLifecycleOwner(lifecycleOwner)
        .setAnimation(MenuAnimation.SHOW_UP_CENTER)
        **.setWidth(ViewGroup.LayoutParams.WRAP_CONTENT)**
            .setShowBackground(false)
            .setBackgroundColor(Color.TRANSPARENT)
        .setMenuRadius(10f)
        .setMenuShadow(10f)
        .build();

How to set width to WRAP_CONTENT?

**Comment by skydoves** [comment]
@airtel121 
Hi,
we can't set the width WRAP_CONTENT.
because the popup windows size would be set firstly and the layout will be inflated on the popup lately. So you should the width size explicitly.

I prefer this solution :
```kotlin

internal fun Context.displaySize(): Point {
  val wm = getSystemService(Context.WINDOW_SERVICE) as WindowManager
  val display = wm.defaultDisplay
  val size = Point()
  display.getSize(size)
  return size
}

. setWidth((context.displaySize().x * 0.7f).toInt())
``` 

I set the menu size using a ratio of the screen size.
