### ISSUE TITLE
Background issue in full-screen mode

### ISSUE THREAD

**Issue by IhorKlimov** [skydoves/PowerMenu#53]
**Please complete the following information:**
- Library Version: 2.0.5
 
**Describe the Bug:**

When app is in a full-screen mode (no navigation bar  and status bar is shown), background scrim of PowerMenu is not shown in full screen, but stops vertically at the point where bottom Android navigation bar would start normally, leaving bottom part of a screen without PowerMenu background

**Expected Behavior:**

Background should be drawn in full-screen

**Comment by skydoves** [comment]
@IhorKlimov 
Hi, sorry for the late reply.
It is hard to implement the behavior.
Could you explain with more details?

<img src="https://user-images.githubusercontent.com/24237865/65700035-f1188b80-e0b9-11e9-8230-63ec956fe6f3.jpg" width="43%"/>

**Comment by ssaqua** [comment]
👋 @skydoves 

I'd like to submit a PR for this.

Here's some more info to reproduce @IhorKlimov 's problem.

In the demo app `MainActivity` if we make some adjustments to the system UI visibility:

```diff
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
+ int visibility = View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
+                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
+                | View.SYSTEM_UI_FLAG_FULLSCREEN
+                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
+                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
+                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE;
+ getWindow().getDecorView().setSystemUiVisibility(visibility);
  setContentView(R.layout.activity_main);

  ...
}
```

(Not all visibility flags will be a problem, I think it's mainly when `SYSTEM_UI_FLAG_LAYOUT_STABLE` is used).

Then we end up with background view being like:

<img src="https://user-images.githubusercontent.com/5179255/66194968-23496f00-e6f2-11e9-8509-397d32cd54dc.png" width="240">

What do you think about adding `setBackgroundSystemUiVisibility(int visibility)` as an option on the builder? Please see PR #56 😃
