### ISSUE TITLE
Kotlin - Global CustomPopMenu variable

### ISSUE THREAD

**Issue by ravirajjak** [skydoves/PowerMenu#55]
How would u dismiss custom popup menu in kotlin ?

**Comment by skydoves** [comment]
@ravirajjak 
It is same as the Java.
Use `dismiss()` function.

**Comment by ravirajjak** [comment]
@skydoves 
no not at all 
Following is  the global declaration in class 
var customPowerMenu: CustomPowerMenu<*, out MenuBaseAdapter<*>>? = null
