### ISSUE TITLE
Many selections

### ISSUE THREAD

**Issue by Astorn12** [skydoves/PowerMenu#57]
Is it possible to be able to select many items at once? I'm using PowerMany as a menu to filter some things.

**Comment by skydoves** [comment]
Sorry for the late reply.
You can run and test it on the demo project.

Hightlighting two items when building a `PowerMenu`.
```java
.addItem(new PowerMenuItem("Profile", true))
.addItem(new PowerMenuItem("Board", true))
.addItem(new PowerMenuItem("Logout", false))
```

**Comment by skydoves** [comment]
#23

**Comment by iAmJuan550** [comment]
Hello @skydoves did you manage to implement the multi-level menus?
