### ISSUE TITLE
Show selected item without dimming it to background

### ISSUE THREAD

**Issue by WenLonG12345** [skydoves/PowerMenu#77]
Hi, want to ask is anyone have idea how to show the item within recyclerview without dimming it? 

![image](https://user-images.githubusercontent.com/39330565/128658500-c2b9c030-4d68-429d-b2ff-30d495d0dfcb.png)

Expected: 
![image](https://user-images.githubusercontent.com/39330565/128658609-efaae0c5-6245-4407-b944-83b5450dcb06.png)

**Comment by skydoves** [comment]
Hi, do you mean this function?

```java
.setShowBackground(false)
```

**Comment by WenLonG12345** [comment]
Hi, not really. You can see from telegram, when user select one of the item from `recyclerview`, the selected item is highlighted and overall background is dimmed. 
Or maybe you have any idea how can I archived this effect?

**Comment by skydoves** [comment]
Ah, do you mean this kind of highlighting? 

https://user-images.githubusercontent.com/24237865/96139358-c524ae00-0f39-11eb-82ff-90a4a734e076.gif

**Comment by WenLonG12345** [comment]
@skydoves Yes! sorry for my poor representation haha. 
How can I archived this effect in this libarry without using `Balloon` ?

**Comment by skydoves** [comment]
I see! The feature should be implemented newly.
I will consider implementing it or your Pull-Request is also welcome.
`Balloon` can implement everything that can be implemented using `PowerMenu`.
It is your choice!

**Comment by WenLonG12345** [comment]
Oh it is a feature request. But I am not sure I have enough experience to do such a pull-request haha. 
I think I will be implementing a custom view in `Balloon` and show it like telegram. 
Going to try now. Thanks! :)

**Comment by skydoves** [comment]
Great :) If you get another issue, please report it!
