### ISSUE TITLE
PopupMenu BackGround is missing 

### ISSUE THREAD

**Issue by mirzaalicdz** [skydoves/PowerMenu#82]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
Hey @mirzaalicdz ,
Could you describe the details of your issue?
And it would be also appreciated if you can attach your Builder class.
Thanks!

**Comment by mirzaalicdz** [comment]
Background Color of popup menu (Popup Window)... i have done with giving background color to item of menu...but still is missing popupWindow  background color opti
![Screenshot 2021-11-15 093241](https://user-images.githubusercontent.com/92848983/141723226-7e4f8251-0a34-41f1-8dcf-98eb612fbd65.png)
on

**Comment by skydoves** [comment]
That is intended because each `PowerMenu` item should have its own background colors.
You can get and change the body of the window by using `getMenuCard` or `getMenuRoot` method.

**Comment by sebastienrouif** [comment]
check https://github.com/skydoves/PowerMenu/pull/64/files for hints on how to apply the style thought MaterialCardView

**Comment by skydoves** [comment]
That would be also a great solution by using the `setIsMaterial(true)` method on your builder. 👍

**Comment by mirzaalicdz** [comment]
Thank you

**Comment by mirzaalicdz** [comment]
Thank you
