### ISSUE TITLE
PowerMenu hides the virtual keyboard

### ISSUE THREAD

**Issue by RobbWatershed** [skydoves/PowerMenu#90]
**Please complete the following information:**
- Library Version : 2.2.0
- Affected Device(s) : All
 
**Describe the Bug:**

To display search history, I use a PowerMenu when the user taps the search field.

At the same time, the device's virtual keyboard appears... behind the PowerMenu, which prevents the user from typing (see below screenshot; it's even more obvious on smaller screen resolutions).

![image](https://user-images.githubusercontent.com/35880555/179172420-fb095cad-481a-4f3a-b1a0-a058a0335626.png)

**Expected Behavior:**

PowerMenu is displayed _behind_ the virtual keyboard, and not the other way around.

**Comment by skydoves** [comment]
This issue was fixed and will be delivered in the next release. Thanks!

**Comment by RobbWatershed** [comment]
Any idea when next release will be ? My users are regularly bringing that up...

**Comment by RobbWatershed** [comment]
Soooo @skydoves, any idea when we can get that one on an official release ?

**Comment by skydoves** [comment]
@RobbWatershed Sorry for the late response. Let me update and publish the next version as soon as possible I can, probably this weekend. Thanks for the reminder!
